### PR TITLE
Support of Swift Package Manager

### PR DESCRIPTION
**Pull request by TwoDollarsEsq**
Adds `Package.swift` file which enables usage with SPM.

### CODE REVIEW

**Review by ZacharyKhan — APPROVED** [review]
Thanks for this!

**Comment by TwoDollarsEsq** [comment]
Please note, that the most correct usage with SPM will be possible only when there is new release that includes `Package.swift`. Until then, dependency can be added by branch or commit hash which is not allowed in published packages.

**Comment by ZacharyKhan** [comment]
@ra1028 will have to push to newest release, I do not have the authorization to do so. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ra1028** [comment]
@ZacharyKhan 
You have a collaborator role, so you can make a new tag  and release.

**Comment by ZacharyKhan** [comment]
>@ZacharyKhan  ...

@ra1028 thank you, but I was referring to updating the cocoa pod trunk. I do not believe I have access to push to this trunk. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ra1028** [comment]
@ZacharyKhan
I'd love to invite you as a maintainer of pods that can submit a new release, since you are now a most active maintainer of this library.

Please send me your email address which registered to pod trunk if you would like.

**Comment by ZacharyKhan** [comment]
No problem, my email is zachary.khan3@gmail.com 

Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ra1028** [comment]
@ZacharyKhan 
I added you as a maintainer of Former.
Keep up the good work Zachary 👍

**Comment by ZacharyKhan** [comment]
Thanks @ra1028, I’ll do my best to keep up with the maintenance of Former 👍🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mattjgalloway** [comment]
@ZacharyKhan , @ra1028 - will one of you do a tag so that those who want to use SPM can do so? That would be great if so! Thanks for adding SPM support!

**Comment by ZacharyKhan** [comment]
I have tagged **1.8.1** as the latest release and updated the podspec. Cocoapods should now have **1.8.1** as the latest version.

**Pull request merged**
